<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2022-02-07T17:37:14-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      permissions.model
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.2.1',
    'version_db_installed' => '20170802000000',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1503413368,
        'latest_version' => '8.2.1',
        'do_page_reindex_check' => false,
        'login_redirect_cid' => 0,
    ],
    'cache' => [
        'blocks' => false,
        'assets' => true,
        'theme_css' => true,
        'overrides' => true,
        'pages' => 'blocks',
        'full_page_lifetime' => 'forever',
        'full_page_lifetime_value' => null,
        'clear' => [
            'thumbnails' => true,
        ],
    ],
    'theme' => [
        'compress_preprocessor_output' => true,
        'generate_less_sourcemap' => false,
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => true,
    ],
    'upload' => [
        'extensions' => '*.flv;*.jpg;*.gif;*.jpeg;*.ico;*.docx;*.xla;*.png;*.psd;*.swf;*.doc;*.txt;*.xls;*.xlsx;*.csv;*.pdf;*.tiff;*.rtf;*.m4a;*.mov;*.wmv;*.mpeg;*.mpg;*.wav;*.3gp;*.avi;*.m4v;*.mp4;*.mp3;*.qt;*.ppt;*.pptx;*.kml;*.xml;*.svg;*.webm;*.ogg;*.ogv;*.vcf',
    ],
    'mail' => [
        'method' => 'smtp',
        'methods' => [
            'smtp' => [
                'server' => 'smtp.office365.com',
                'username' => 'admin@mpopc.com',
                'password' => 'Ad#582or',
                'port' => '25',
                'encryption' => 'SSL',
                'messages_per_connection' => 5000000000000000000,
            ],
        ],
    ],
    'debug' => [
        'detail' => 'message',
        'display_errors' => true,
    ],
    'log' => [
        'errors' => 1,
        'emails' => 1,
        'queries' => [
            'log' => 1,
            'clear_on_reload' => 1,
        ],
    ],
    'permissions' => [
        'model' => 'advanced',
    ],
];
