<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-05-03T16:38:38-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      global_param.auto_show
 * @group     magic_tabs
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'global_param' => [
        'accordion_default_open' => '0',
        'accordion_always_open' => '0',
        'preserve_grid_box' => '1',
        'grid_classes_to_remove' => 'container',
        'wrap_with_grid_box' => '0',
        'mobile_no_transitions' => '0',
        'auto_show' => '1',
    ],
];
