<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-08-11T11:45:09-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      enabled
 * @group     poptin
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'enabled' => true,
];
