<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-09-28T06:25:42-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.editor.ckeditor4.plugins.selected
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'MPO',
            'seo' => [
                'canonical_url' => 'https://mpopc.com/',
                'canonical_url_alternative' => '',
                'tracking' => [
                    'code' => [
                        'header' => '<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':
new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=
\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,\'script\',\'dataLayer\',\'GTM-MNRGXKX\');</script>
<!-- End Google Tag Manager -->

--------------
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':
new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=
\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,\'script\',\'dataLayer\',\'GTM-5GS49TL\');</script>
<!-- End Google Tag Manager -->

<meta name="google-site-verification" content="85KfXeCQsLl581qpk91DopI0UlEPKZQ7RxksHFoOOp8" />

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Attorney",
  "name": "Midgett Preti Olansen",
  "image": "https://mpopc.com/application/files/thumbnails/large/2915/0818/2097/MPO_final.jpg",
  "@id": "https://www.linkedin.com/company/midgett-&-preti-pc",
  "url": "https://mpopc.com/",
  "telephone": "(757)687-8888",
  "priceRange": "$$",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "2901 S Lynnhaven Rd Ste 120",
    "addressLocality": "Virginia Beach",
    "addressRegion": "VA",
    "postalCode": "23452",
    "addressCountry": "US"
  },
  "geo": {
    "@type": "GeoCoordinates",
    "latitude": 36.8321689,
    "longitude": -76.0715013
  },
  "openingHoursSpecification": {
    "@type": "OpeningHoursSpecification",
    "dayOfWeek": [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday"
    ],
    "opens": "08:30",
    "closes": "17:00"
  } 
}
</script>
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "Merchant logo Midgett Preti Olansen",
  "url": "https://mpopc.com/",
  "logo": "https://mpopc.com/application/files/thumbnails/large/2915/0818/2097/MPO_final.jpg",
  "sameAs": [
    "https://www.facebook.com/MidgettPretiOlansen",
    "https://www.linkedin.com/company/midgett-&-preti-pc"
  ]
}
</script>

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://mpopc.com/blog"
  },
  "headline": "Estate Planning Attorney Blog | Midgett Preti Olansen PC",
  "description": "Read articles about corporate law, estate planning law, Probate law, etc., crafted by Midgett Preti Olansen, a top law firm in Virginia Beach.",
  "image": "https://mpopc.com/application/files/thumbnails/large/2915/0818/2097/MPO_final.jpg",  
  "author": {
    "@type": "Organization",
    "name": "Midgett Preti Olansen PC"
  },  
  "publisher": {
    "@type": "Organization",
    "name": "Midgett Preti Olansen PC",
    "logo": {
      "@type": "ImageObject",
      "url": "https://mpopc.com/application/files/thumbnails/large/2915/0818/2097/MPO_final.jpg"
    }
  },
  "datePublished": "2020-12-02",
  "dateModified": "2020-12-02"
}
</script>

<!-- Global site tag (gtag.js) - Google Ads: 461860416 -->
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-461860416"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag(\'js\', new Date());

  gtag(\'config\', \'AW-461860416\');
</script>',
                        'footer' => '',
                    ],
                ],
            ],
            'misc' => [
                'favicon_fid' => 109,
                'iphone_home_screen_thumbnail_fid' => 108,
                'modern_tile_thumbnail_fid' => 110,
                'modern_tile_thumbnail_bgcolor' => 'rgb(255, 255, 255)',
            ],
            'editor' => [
                'concrete' => [
                    'enable_filemanager' => '1',
                    'enable_sitemap' => '1',
                ],
                'ckeditor4' => [
                    'plugins' => [
                        'selected' => [
                            'concrete5filemanager',
                            'concrete5inline',
                            'concrete5uploadimage',
                            'dialogadvtab',
                            'divarea',
                            'floatingspace',
                            'normalizeonchange',
                            'resize',
                            'toolbar',
                            'wysiwygarea',
                            'autogrow',
                            'a11yhelp',
                            'basicstyles',
                            'colordialog',
                            'contextmenu',
                            'elementspath',
                            'enterkey',
                            'entities',
                            'format',
                            'htmlwriter',
                            'image',
                            'indentblock',
                            'indentlist',
                            'justify',
                            'list',
                            'liststyle',
                            'magicline',
                            'removeformat',
                            'showblocks',
                            'showborders',
                            'sourcearea',
                            'sourcedialog',
                            'stylescombo',
                            'tab',
                            'table',
                            'tableresize',
                            'tableselection',
                            'tabletools',
                            'undo',
                            'concrete5link',
                            'concrete5styles',
                        ],
                    ],
                ],
            ],
        ],
    ],
];
